---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
on:
  release:
    types: [ published, unpublished ]
  push:
    branches:
      - 'main'
    tags:
      - '*'

defaults:
  run:
    working-directory: 'vnode.ypserver'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          path: 'vnode.ypserver'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Ansible Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          --branch main
          $(echo ${{ github.repository }} | cut -d/ -f1 )
          $(echo ${{ github.repository }} | cut -d/ -f2 )
